parameters:
    # Adds a fallback VARNISH_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(VARNISH_URL): ''
    env(ELASTICSEARCH_HOST): 'http://elasticsearch:9200'
    env(ELASTICSEARCH_HOST_FULL): '%env(ELASTICSEARCH_HOST)'

api_platform:
    mercure:
        hub_url: '%env(MERCURE_SUBSCRIBE_URL)%'
    elasticsearch:
        hosts: ['%env(ELASTICSEARCH_HOST_FULL)%']
    mapping:
        paths:
        - '%kernel.project_dir%/config/packages/api_platform'
    resource_class_directories:
        - '%kernel.project_dir%/src/Entity'
        - '%kernel.project_dir%/src/Models'
    title: Hello API Platform
    version: 1.0.0
     Enable the Varnish integration
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
doctrine:
    orm:
        filters:
            user_filter:
                class: App\Filter\SearchFilter
