parameters:
    # Adds a fallback VARNISH_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(VARNISH_URL): ''
    env(ELASTICSEARCH_HOST): 'http://elasticsearch:9200'

api_platform:
    elasticsearch:
        hosts: ['%env(ELASTICSEARCH_HOST)%']
    mapping:
        paths:
        - '%kernel.project_dir%/config/packages/api_platform'
    resource_class_directories:
        - '%kernel.project_dir%/src/Entity'
        - '%kernel.project_dir%/src/Models'
    title: Hello API Platform
    version: 1.0.0
     Enable the Varnish integration
    http_cache:
        invalidation:
            enabled: true
            varnish_urls: ['%env(VARNISH_URL)%']
        max_age: 0
        shared_max_age: 3600
        vary: ['Content-Type', 'Authorization']
        public: true
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
doctrine:
    orm:
        filters:
            user_filter:
                class: App\Filter\SearchFilter
