services:
  objective.search_filter:
    parent: 'api_platform.doctrine.orm.search_filter'
    arguments:
      - {bnet_user: 'exact'}
    tags: [ 'api_platform.filter' ]

  message.order_filter:
    parent: 'api_platform.doctrine.orm.order_filter'
    arguments:
      - {id: 'DESC'}
    tags: [ 'api_platform.filter' ]

