App\Entity\User:
    itemOperations:
        get: ~
        put: ~
        delete: ~
    collectionOperations:
        get: ~
        post: ~
        user_security:
            method: GET
            path: /users/security
            controller: 'App\Controller\Api\UserSecurityAction'

