App\Entity\User:
    itemOperations:
#        user_security:
#            method: GET
#            path: /users/security
#            controller: 'App\Controller\UserSecurityAction'
        get: ~
        put: ~
        delete: ~
    collectionOperations:
        get: ~
        post: ~
