App\Entity\User:
    itemOperations:
        get: ~
        put: ~
    collectionOperations:
        user_security:
            method: GET
            path: /users/security
            controller: 'App\Controller\Api\UserSecurityAction'
            swagger_context:
                summary: "Retrieve a user list with specific filters"
                description: "Retrieve a user list with username, password and api_key filters"

App\Entity\Realm:
    itemOperations:
        get: ~
    collectionOperations:
        get: ~

App\Entity\Character:
    itemOperations:
        get: ~
    collectionOperations:
        get:
            controller: 'App\Controller\Api\BlankAction'
            swagger_context:
                summary: "Disabled action, will always return null"
                description: "Disabled action, will always return null"
        character_guild:
            method: GET
            path: /characters/{id}/guild
            controller: 'App\Controller\Api\DefaultAction'
            swagger_context:
                summary: "Retrieve an achievement list with specific filters for a character"
                description: "Retrieve an achievement list with specific filters for a character"
        character_achievements:
            method: GET
            path: /characters/{id}/achievements
            controller: 'App\Controller\Api\DefaultAction'
            swagger_context:
                summary: "Retrieve an achievement list with specific filters for a character"
                description: "Retrieve an achievement list with specific filters for a character"
        character_completed_achievements:
            method: GET
            path: /characters/{id}/achievements/completed
            controller: 'App\Controller\Api\DefaultAction'
            swagger_context:
                summary: "Retrieve an achievement list with specific filters for a character"
                description: "Retrieve an achievement list with specific filters for a character"
        character_feeds:
            method: GET
            path: /characters/{character}/feeds
            controller: 'App\Controller\Api\DefaultAction'
            swagger_context:
                summary: "Retrieve a list of feed with specific filters for a character"
                description: "Retrieve an achievement list with specific filters for a character"

App\Entity\Achievement:
    itemOperations:
        get: ~
    collectionOperations:
        get:
            controller: 'App\Controller\Api\BlankAction'
            swagger_context:
                summary: "Disabled action, will always return null"
                description: "Disabled action, will always return null"

App\Entity\Classes:
    itemOperations:
        get:
            controller: 'App\Controller\Api\BlankAction'
            swagger_context:
                summary: "Disabled action, will always return null"
                description: "Disabled action, will always return null"
    collectionOperations:
        get: ~

App\Entity\Race:
    itemOperations:
        get:
            controller: 'App\Controller\Api\BlankAction'
            swagger_context:
                summary: "Disabled action, will always return null"
                description: "Disabled action, will always return null"
    collectionOperations:
        get: ~


App\Entity\Items:
    itemOperations:
        character_items:
            method: GET
            path: /characters/{id}/items
            controller: 'App\Controller\Api\DefaultAction'
            swagger_context:
                summary: "Retrieve items with specific filters for a character"
                description: "Retrieve items with specific filters for a character"
    collectionOperations:
        get:
            controller: 'App\Controller\Api\BlankAction'
            swagger_context:
                summary: "Disabled action, will always return null"
                description: "Disabled action, will always return null"

App\Entity\Stats:
    itemOperations:
        character_stats:
            method: GET
            path: /characters/{id}/stats
            controller: 'App\Controller\Api\DefaultAction'
            swagger_context:
                summary: "Retrieve stats with specific filters for a character"
                description: "Retrieve stats with specific filters for a character"
    collectionOperations:
        get:
            controller: 'App\Controller\Api\BlankAction'
            swagger_context:
                summary: "Disabled action, will always return null"
                description: "Disabled action, will always return null"

App\Entity\Objective:
  collectionOperations:
    get:
      filters: ['objective.search_filter']
    post: ~

